### ISSUE TITLE
Makefile?

### ISSUE THREAD

**Issue by misantrop76** [Tuteurs101/Code-Review#61]
**Fichier :** 

**Code source :**
```
SRCS		=	main_wolf.c
SRCS		+=	ft_init.c
SRCS		+=	ft_init_hub.c
SRCS		+=	ft_init_weapon.c
SRCS		+=	ft_init_texture.c
SRCS		+=	ft_fill_map.c
SRCS		+=	ft_map.c
SRCS		+=	ft_keys.c
SRCS		+=	ft_move.c
SRCS		+=	ft_teleport.c
SRCS		+=	ft_ray.c
SRCS		+=	ft_wall.c
SRCS		+=	ft_draw_wall.c
SRCS		+=	ft_spawn.c
SRCS		+=	ft_textures.c
SRCS		+=	ft_gameover.c
SRCS		+=	ft_usage.c
```
??
```
CODE HERE
```

**Details (optionnel) :**
??

**Comment by misantrop76** [comment]
Le makefile est trop sexy

**Comment by Tuteurs101** [comment]
Un rangement des noms de fichiers suivant offre une bonne lisibilité et une plus grande simplicité de recherche des fichiers conçernés. Potentiellement, un classement par ordre alphabetique peut être un plus pour les projets demandant un grand nombre de fichiers.
